name: graphql_bloc
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^2.0.1
  meta: ^1.1.8
  equatable: ^1.0.0
  shared_preferences: ^0.5.4+5
  graphql_flutter: ^2.1.1-beta.4
  path_provider: ^1.4.4

dependency_overrides:
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true